version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: postgres-db
      POSTGRES_USER: emrah
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data